name: Lint Code Base

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
  pull_request:
    branches: 
      - master
      - feature/*
      - hotfix/*
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'javascript', 'python', 'css', 'dockerfile' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up cache for Node modules
        if: matrix.language == 'javascript'
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT: ${{ matrix.language == 'javascript' }}
          VALIDATE_PYTHON: ${{ matrix.language == 'python' }}
          VALIDATE_CSS: ${{ matrix.language == 'css' }}
          VALIDATE_DOCKER: ${{ matrix.language == 'dockerfile' }}
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
